# Generated by Django 5.0 on 2023-12-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0001_initial'),
        ('companies', '0001_initial'),
        ('courses', '0001_initial'),
        ('jobs', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='images/avatar-default.png', upload_to='images/')),
                ('certificates', models.ManyToManyField(to='certificates.certificate')),
                ('companies', models.ManyToManyField(to='companies.copmany')),
                ('courses', models.ManyToManyField(to='courses.course')),
                ('jobs', models.ManyToManyField(to='jobs.job')),
                ('skills', models.ManyToManyField(to='skills.skill')),
            ],
        ),
    ]
