# Generated by Django 5.0 on 2023-12-24 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('majors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Copmany',
            new_name='Company',
        ),
    ]
