# Generated by Django 5.0 on 2023-12-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_rename_copmany_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_image',
            field=models.ImageField(default='images/avatar-default.png', upload_to='images/'),
        ),
    ]
