# Generated by Django 5.0 on 2024-01-02 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_post_image_post_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
